language: node_js
node_js:
  # https://github.com/nodejs/LTS
  - "6" # ends April 2019
  - "8" # ends December 2019
  - "10" # ends April 2021

sudo: false

script:
  - npm test -- --allow-chrome-as-root
